3.3.3alpha2

diff --git a/src/x3270/pr3287/configure b/src/x3270/pr3287/configure
--- a/src/x3270/pr3287/configure
+++ b/src/x3270/pr3287/configure
@@ -826,12 +826,14 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --disable-dbcs          leave out DBCS support
   --disable-ssl           leave out OpenSSL support
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-ssl=DIR          specify OpenSSL install directory
+  --with-icu=DIR          specify ICU install directory
 
 Some influential environment variables:
   CC          C compiler command
@@ -2112,12 +2114,16 @@ solaris2*)	XANSI=-D__EXTENSIONS__
 		;;
 darwin*)	XPRECOMP=-no-cpp-precomp
 		;;
-linux*)		XANSI="-D_BSD_SOURCE -D_POSIX_SOURCE"
+linux*)		XANSI="-D_BSD_SOURCE -D_POSIX_SOURCE -D_XOPEN_SOURCE"
 		;;
 *)		XANSI=""
 		;;
 esac
 
+
+
+# Set up the configuration directory.
+LIBX3270DIR='${sysconfdir}/x3270'
 
 
 
@@ -2970,6 +2976,328 @@ echo "$as_me: WARNING: Disabling OpenSSL" >&2;}
 	fi
 fi
 
+
+# Check whether --with-icu or --without-icu was given.
+if test "${with_icu+set}" = set; then
+  withval="$with_icu"
+
+fi;
+if test "$enable_dbcs" != no
+then	orig_CPPFLAGS="$CPPFLAGS"
+	unset any
+	for dir in "$with_icu" /usr/local /usr/local/icu /usr/lib/icu /usr/pkg/icu /usr/icu /var/icu /opt/icu
+	do	header_fail=0
+		if test -n "$dir" -a ! -d "$dir/include"
+		then	header_fail=1
+			continue
+		fi
+		if test -n "$any"
+		then	{ echo "$as_me:$LINENO: retrying with -I$dir/include" >&5
+echo "$as_me: retrying with -I$dir/include" >&6;}
+		fi
+		if test -n "$dir"
+		then	CPPFLAGS="$orig_CPPFLAGS -I$dir/include"
+		fi
+
+for ac_header in unicode/ucnv.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <$ac_header>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=$ac_header_preproc"
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+else
+  header_fail=1
+fi
+
+done
+
+		if test "$header_fail" -eq 0
+		then	break
+		fi
+		unset `echo ac_cv_header_unicode/ucnv_h | $as_tr_sh`
+		CPPFLAGS="$orig_CPPFLAGS"
+		any=1
+	done
+	if test $header_fail -eq 1
+	then	{ echo "$as_me:$LINENO: WARNING: Disabling DBCS" >&5
+echo "$as_me: WARNING: Disabling DBCS" >&2;}
+		enable_dbcs="no"
+	fi
+fi
+
+# Figure out the ICU version, which depends on having found the ICU header
+# files above.
+if test "$enable_dbcs" != no
+then	echo "$as_me:$LINENO: checking for ICU version strings" >&5
+echo $ECHO_N "checking for ICU version strings... $ECHO_C" >&6
+	cat >/tmp/icutst$$.c <<EOF
+#include "unicode/ucnv.h"
+#define xstr(s)	str(s)
+#define str(s)	#s
+int
+main(int argc, char *argv)
+{
+	printf("%s %s\n", xstr(U_ICU_VERSION_SUFFIX), U_ICUDATA_NAME);
+	return 0;
+}
+EOF
+	fail=0
+	${CC} ${CPPFLAGS} -o /tmp/icutst$$ /tmp/icutst$$.c || fail=1
+	rm -f /tmp/icutst$$.c
+	if test "$fail" != 1
+	then	icu_suffix=`/tmp/icutst$$ | awk '{print $1}'`
+		ICU_DATA_PREFIX=`/tmp/icutst$$ | awk '{print $2}'`
+		rm -f /tmp/icutst$$
+		if test -z "$icu_suffix" -o -z "$ICU_DATA_PREFIX"
+		then	fail=1
+		fi
+	fi
+	if test "$fail" -eq 0
+	then	echo "$as_me:$LINENO: result: $icu_suffix, $ICU_DATA_PREFIX" >&5
+echo "${ECHO_T}$icu_suffix, $ICU_DATA_PREFIX" >&6
+	else	echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+		{ echo "$as_me:$LINENO: WARNING: Disabling DBCS" >&5
+echo "$as_me: WARNING: Disabling DBCS" >&2;}
+		enable_dbcs="no"
+	fi
+	if test "$enable_dbcs" != "no"
+	then	icu_enough=`expr $icu_suffix '>=' _2_2`
+		if test $icu_enough -eq 0
+		then    { echo "$as_me:$LINENO: WARNING: ICU version must be 2.2 or later" >&5
+echo "$as_me: WARNING: ICU version must be 2.2 or later" >&2;}
+			{ echo "$as_me:$LINENO: WARNING: Disabling DBCS" >&5
+echo "$as_me: WARNING: Disabling DBCS" >&2;}
+			enable_dbcs="no"
+		fi
+	fi
+fi
+
+# Check for ICU libraries.
+if test "$enable_dbcs" != no
+then	orig_LDFLAGS="$LDFLAGS"
+	unset any
+	for dir in "$with_icu" /usr/local /usr/local/icu /usr/pkg/icu /usr/icu /var/icu /opt/icu
+	do	lib_fail=0
+		if test -n "$dir" -a ! -d "$dir/lib"
+		then	lib_fail=1
+			continue
+		fi
+		if test -n "$any"
+		then	{ echo "$as_me:$LINENO: retrying with -L$dir/lib" >&5
+echo "$as_me: retrying with -L$dir/lib" >&6;}
+		fi
+		if test -n "$dir"
+		then	LDFLAGS="$orig_LDFLAGS -L$dir/lib"
+		fi
+
+as_ac_Lib=`echo "ac_cv_lib_icui18n_ucnv_open${icu_suffix}" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for ucnv_open${icu_suffix} in -licui18n" >&5
+echo $ECHO_N "checking for ucnv_open${icu_suffix} in -licui18n... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Lib+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-licui18n  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char ucnv_open${icu_suffix} ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+ucnv_open${icu_suffix} ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_Lib=yes"
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+eval "$as_ac_Lib=no"
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Lib'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Lib'}'`" >&6
+if test `eval echo '${'$as_ac_Lib'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBICUI18N 1
+_ACEOF
+
+  LIBS="-licui18n $LIBS"
+
+else
+  lib_fail=1
+fi
+
+		if test "$lib_fail" -eq 0
+		then	break
+		fi
+		unset `echo ac_cv_lib_icui18n_ucnv_open${icu_suffix} | $as_tr_sh`
+		LDFLAGS="$orig_LDFLAGS"
+		any=1
+	done
+	if test $lib_fail -eq 1
+	then	{ echo "$as_me:$LINENO: WARNING: Disabling DBCS" >&5
+echo "$as_me: WARNING: Disabling DBCS" >&2;}
+		enable_dbcs="no"
+	fi
+fi
+
+# Check whether --enable-dbcs or --disable-dbcs was given.
+if test "${enable_dbcs+set}" = set; then
+  enableval="$enable_dbcs"
+
+fi;
+case "$enable_dbcs" in
+no)	CNV="#"
+	;;
+*)	cat >>confdefs.h <<\_ACEOF
+#define X3270_DBCS 1
+_ACEOF
+
+	DBCS_C="wide.c"
+	DBCS_O="wide.o"
+	CNV=""
+	DBCS=-DX3270_DBCS=1
+	;;
+esac
+
+
+
+
+
 # Check whether --enable-ssl or --disable-ssl was given.
 if test "${enable_ssl+set}" = set; then
   enableval="$enable_ssl"
@@ -3581,7 +3909,13 @@ s,@host_vendor@,$host_vendor,;t t
 s,@host_os@,$host_os,;t t
 s,@XANSI@,$XANSI,;t t
 s,@XPRECOMP@,$XPRECOMP,;t t
+s,@LIBX3270DIR@,$LIBX3270DIR,;t t
 s,@CPP@,$CPP,;t t
+s,@DBCS_C@,$DBCS_C,;t t
+s,@DBCS_O@,$DBCS_O,;t t
+s,@CNV@,$CNV,;t t
+s,@ICU_DATA_PREFIX@,$ICU_DATA_PREFIX,;t t
+s,@DBCS@,$DBCS,;t t
 s,@SSL@,$SSL,;t t
 CEOF
 
